### ISSUE TITLE
Desktop Notifications

### ISSUE THREAD

**Issue by whereswaldon** [arborchat/muscadine#20]
When someone replies to a message that you wrote, `muscadine` could use `notify-send` or similar to generate a desktop notification. This would help users know when there is activity on the server. Right now, you'll never know if the TUI isn't on-screen (and maybe not even then).

**Comment by Caton101** [comment]
I will do this!

**Comment by whereswaldon** [comment]
#31 Added basic support. There are more enhancements that could be made, but the foundation is in place. I'm going to close this in favor of more specific future feature requests. Thanks @Caton101 for your help!

**Comment by Caton101** [comment]
This is still an issue
