### ISSUE TITLE
Only generate desktop notifications for recent messages

### ISSUE THREAD

**Issue by whereswaldon** [arborchat/muscadine#32]
When the chat client receives *any* new message, no matter its age, it notifies the user with a desktop notification. While this initially doesn't seem problematic, this occurs when the client queries for old message history (could be messages from days ago), and it doesn't make sense to notify for those. It'd be great if the notifications only were generated for messages from within the past minute of real time.

This is really just a matter of changing [this line](https://github.com/arborchat/muscadine/blob/master/client.go#L76) to do some comparison using the [`time`](https://godoc.org/time) package.

**Comment by Caton101** [comment]
this was fixed with my recent pull request

**Comment by whereswaldon** [comment]
You're so right.
