### ISSUE TITLE
Pasting freaks out

### ISSUE THREAD

**Issue by jwhett** [arborchat/muscadine#36]
## Expected behavior

Pasting into chat renders text correctly.

## Current behavior

Pasting into chat freaks the client out like it's typing too fast and inserts spaces intermittently...

![image](https://user-images.githubusercontent.com/4229885/49124503-b15ef880-f28a-11e8-85b0-e594cc660921.png)

**Comment by whereswaldon** [comment]
I think this is a bug in `gocui.DefaultEditor`. Need to chase this down, as it's a significant UX problem. Ugh.
