### ISSUE TITLE
Trap SIGINT and send "disconnect" message

### ISSUE THREAD

**Issue by jwhett** [arborchat/muscadine#42]
As an `observer`
I would like `to see when clients disconnect`
so that `I know who has recently gone offline without a list of connected clients`.

## Example

- Intercept SIGINT and send a unique _disconnect_ message, like "jwhett: [[ DISCONNECTED ]]"

**Comment by whereswaldon** [comment]
I think it's worth noting that Ctrl+C actually isn't sending SIGINT. It's handling the keypresses directly. (or, maybe gocui is transparent handling sigint for me). Either way, this logic actually belongs in the `quit` handler function.
