### ISSUE TITLE
Bug: One-less character

### ISSUE THREAD

**Issue by jwhett** [arborchat/muscadine#62]
## Expected Behavior

- Type message
- Full message is rendered in display

## Current Behavior

- Type message
- All but last character in message is rendered after send

<img width="179" alt="screen shot 2018-12-29 at 11 48 54 am" src="https://user-images.githubusercontent.com/4229885/50540433-bfd95200-0b5f-11e9-9663-f9b9b69e2b96.png">

**Comment by Caton101** [comment]
Have you tried running `dep ensure`?

**Comment by aThorp96** [comment]
I am also experiencing this. On commit `2308ba2c469bf4636f63f8d2a9b1897ca3ad8a89`.

**Comment by whereswaldon** [comment]
I think this is coming from [this line](https://github.com/arborchat/muscadine/blob/master/tui/tui.go#L335), which was intended to strip out the final newline character in messages. I'm not sure what has changed...
