### ISSUE TITLE
Fix Issue Templates

### ISSUE THREAD

**Issue by jwhett** [arborchat/muscadine#67]
The template format has changed since I last wrote them. All templates in #63 for issues are invalid. I've tried to trigger the PR templates without success, but I'll address that in a different issue.

The following changes need to be made:

- Add `name`
- Add `about`

These new fields must be populated and `name` must be unique. Appears the `name` field is the new `title` field and must also be unique.

**Example**

The header for files in `.github/ISSUE_TEMPLATE/` should look something like this:

```
---
name: Bug report
about: Create a report to help us improve
title: ''
labels: bug
assignees: ''

---
```

**Comment by whereswaldon** [comment]
I believe this is complete since #83, so I'm going to close it for now
