### ISSUE TITLE
Scrolling issues in message history pane

### ISSUE THREAD

**Issue by jwhett** [arborchat/muscadine#7]
## Expected behavior

- text reaches bottom of the chat pane
- send new message
- pane shows latest message sent

## Current behavior

- text reaches bottom of the chat pane
- send new message
- pane scrolls, but one message is hidden.

![Screen shot here.](https://user-images.githubusercontent.com/4229885/48038429-8d524080-e13e-11e8-89a7-d7ec4879f4f5.png)

Can't see "first line" without sending "second line." Screen shot has an additional line sent after "second line."

**Comment by whereswaldon** [comment]
This should be fixed by 1371465, care to retest?

**Comment by jwhett** [comment]
totes fixed
