### ISSUE TITLE
Update the screenshot

### ISSUE THREAD

**Issue by Caton101** [arborchat/muscadine#72]
The screenshot in the current readme is very old and the top of the TUI has changed since the time the image was taken. New users may be confused about why the program looks so different from the current version. The task of updating the screenshot would also include updating the readme with information about the new screen elements.

I think this would be a very easy task to complete. In order to avoid distracting others, I'll work on this issue tomorrow and make a PR.

**Comment by whereswaldon** [comment]
Great idea! My one word of warning is that you should get the consent of anyone whose messages appear in your screenshot. You're welcome to use mine, but anyone else may not be comfortable with that. To take the current one, I used a local server and wrote all the messages from two clients.

**Comment by Caton101** [comment]
My plan was to recreate the current screenshot using a local server. I guess I didn’t think about asking for permission first. If it is ok with you, may I use the text in the current screenshot?

On Jan 4, 2019, at 11:34 PM, Christopher Waldon <notifications@github.com<mailto:notifications@github.com>> wrote:


Great idea! My one word of warning is that you should get the consent of anyone whose messages appear in your screenshot. You're welcome to use mine, but anyone else may not be comfortable with that. To take the current one, I used a local server and wrote all the messages from two clients.

**Comment by whereswaldon** [comment]
You're welcome to replicate it!
